AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvType:
    Description: "Environment type"
    Type: String
  HostedZoneId:
    Description: "Route53 HostedZone ID"
    Type: String
  BaseDomain:
    Description: "Based domain of application"
    Type: String

Conditions:
  isProduction: !Equals [ !Ref EnvType, 'production' ]

Mappings:
  RegionMap:
    us-east-1:
      S3HostedZoneID: Z3AQBSTGFYJSTF
      WebsiteEndpoint: s3-website-us-east-1.amazonaws.com
    us-west-1:
      S3HostedZoneID: Z2F56UZL2M1ACD
      WebsiteEndpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3HostedZoneID: Z3BJ6K6RIION7M
      WebsiteEndpoint: s3-website-us-west-2.amazonaws.com
    eu-west-1:
      S3HostedZoneID: Z1BKCTXD74EZPE
      WebsiteEndpoint: s3-website-eu-west-1.amazonaws.com
    ap-southeast-1:
      S3HostedZoneID: Z3O0J2DXBE1FTB
      WebsiteEndpoint: s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      S3HostedZoneID: Z1WCIGYICN2BYD
      WebsiteEndpoint: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-1:
      S3HostedZoneID: Z2M4EHUR26P7ZW
      WebsiteEndpoint: s3-website-ap-northeast-1.amazonaws.com
    sa-east-1:
      S3HostedZoneID: Z31GFT0UA1I2HV
      WebsiteEndpoint: s3-website-sa-east-1.amazonaws.com

Resources:
  DocBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [isProduction,
        !Join [ ".", [ "doc", !Ref BaseDomain ]],
        !Join [ ".", [ "doc", !Ref EnvType, !Ref BaseDomain ]]
      ]
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  DocBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DocBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Join [ "", ["arn:aws:s3:::", !Ref DocBucket, "/*"] ]
            Principal: "*"

  DocDeployerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "DocDeployerUser"

  DeployWebAppPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DeployDocumentation
      Users:
      - !Ref DocDeployerUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: [
            !Join [ "", ["arn:aws:s3:::", !Ref DocBucket] ],
            !Join [ "", ["arn:aws:s3:::", !Ref DocBucket, "/*"] ]
          ]

  EnvDomainRecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: "Zone for dynamic resolution manage by CloudFormation"
      RecordSets:
        -
          Name: !If [isProduction,
            !Join [ ".", [ "doc", !Ref BaseDomain ]],
            !Join [ ".", [ "doc", !Ref EnvType, !Ref BaseDomain ]]
          ]
          Type: A
          AliasTarget:
            HostedZoneId: !FindInMap [ RegionMap, !Ref 'AWS::Region', S3HostedZoneID]
            DNSName: !FindInMap [ RegionMap, !Ref 'AWS::Region', WebsiteEndpoint]
